language: php

php: [5.4, 5.5, hhvm]

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer install --dev --prefer-source

script:
  - phpspec run -fdot

notifications:
  email:
    - benjamin.grandfond@gmail.com